[window]
blur = false
opacity = 0.8
padding.x = 10
padding.y = 10
[window.dimensions]
columns = 140
lines = 30
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "regular" }
size = 6.5
[colors]
  # Catppuccin Macchiato (Base Colors)
  primary.background = "#24273A"  # Base
  primary.foreground = "#CAD3F5"  # Text
  cursor.text        = "#24273A"  # Cursor Text (Background)
  cursor.cursor      = "#F4DBD6"  # Cursor (Rosewater)

  # Normal Colors
  normal.black   = "#494D64"  # Surface1
  normal.red     = "#ED8796"  # Red
  normal.green   = "#A6DA95"  # Green
  normal.yellow  = "#EED49F"  # Yellow
  normal.blue    = "#8AADF4"  # Blue
  normal.magenta = "#F5BDE6"  # Pink
  normal.cyan    = "#8BD5CA"  # Teal
  normal.white   = "#B8C0E0"  # Subtext1

  # Bright Colors
  bright.black   = "#5B6078"  # Surface2
  bright.red     = "#ED8796"  # Red (Bright)
  bright.green   = "#A6DA95"  # Green (Bright)
  bright.yellow  = "#EED49F"  # Yellow (Bright)
  bright.blue    = "#8AADF4"  # Blue (Bright)
  bright.magenta = "#F5BDE6"  # Pink (Bright)
  bright.cyan    = "#8BD5CA"  # Teal (Bright)
  bright.white   = "#A5ADCB"  # Subtext0

  # Dim Colors (Optional, for less contrast)
  dim.black   = "#494D64"  # Surface1 (Dim)
  dim.red     = "#ED8796"  # Red (Dim)
  dim.green   = "#A6DA95"  # Green (Dim)
  dim.yellow  = "#EED49F"  # Yellow (Dim)
  dim.blue    = "#8AADF4"  # Blue (Dim)
  dim.magenta = "#F5BDE6"  # Pink (Dim)
  dim.cyan    = "#8BD5CA"  # Teal (Dim)
  dim.white   = "#B8C0E0"  # Subtext1 (Dim)

[cursor]
style.shape = "underline"
style.blinking = "On"
#color.cursor = "#F4DBD6"  # Rosewater
